### ISSUE TITLE
How do you launch it?

### ISSUE THREAD

**Issue by ZVH1** [LeviTheOtaku/global-lagswitch#1]
I open .Push to git.cmd nut nothing happens.

**Comment by LeviTheOtaku** [comment]
hey sorry.
push to git.cmd
is my bat for quickly updating the github page. run lagswitch.exe
you can get the files you ened from releases

**Comment by LeviTheOtaku** [comment]
https://github.com/LeviTheOtaku/global-lagswitch/releases/download/v0.0.3/Global.Lagswitch.exe
