### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by ZVH1** [LeviTheOtaku/global-lagswitch#2]
I run it and it says run as admin even if I click run as administrator.

**Comment by LeviTheOtaku** [comment]
this could be caused by issues with your firewall.
does your user have access to firewall settings?

**Comment by ZVH1** [comment]
Ummm... This is a private computer. I guess? How would I allow it?

**Comment by Evulpes** [comment]
The "run as administrator" error is a generic error from an undefined catch block. It's likely that the dependency libraries are blocked.

**Comment by LeviTheOtaku** [comment]
i've changed the way errors are logged.
if you still have any problems, open a new issue.
