### ISSUE TITLE
Not starting to lag

### ISSUE THREAD

**Issue by Krokolol12** [LeviTheOtaku/global-lagswitch#3]
everytime i am trying to start to lag a programm, i get this error
![Screenshot](https://user-images.githubusercontent.com/82370414/114364183-6ef79700-9b79-11eb-9177-61d43ed0c360.png)

**Comment by Krokolol12** [comment]
sry its german:
System.ComponentModel.Win32Exception (0x80004005): A 32-Bit-process can not acces modules of a 64-Bit-process.
bei = at

**Comment by LeviTheOtaku** [comment]
i've added a 32-bit version of the exe, you can try and use that.
if it doesn't work. it means the program isn't supported.

**Comment by Krokolol12** [comment]
ok, so i've tried it again, and it gave me the same error(i used the 32 bit version). My pc runs on a 64-bi system, so i think, that maybe the first download might also start as a 32-Bit process, but i am not sure, i don't realy know that much about this kind of stuff.
